cd /nfs/dust/cms/user/jabuschh/PhD/ttbar/genstudy/CMSSW_9_4_6/src/UserCode/TopAnalysis/analyzer/SMEFT/cfg/
cmsRun analyzer_WILSONCOEFFICIENT_ditopmass300to1000.py
cmsRun analyzer_WILSONCOEFFICIENT_ditopmass1000to2000.py
cmsRun analyzer_WILSONCOEFFICIENT_ditopmass2000to7000.py
