./EFTweightdistr.sh
./EFTweightdistr_logscale.sh
./EFTweights_mean.sh
./chisquare.sh
./ditopmass.sh
./ditopmass_logscale.sh
./ditopmass_normalized.sh
./ditopmass_normalized_logscale.sh
./sensitivity.sh
./sensitivity_normalizedmtt.sh
